#!/usr/bin/env python3
"""Interactively initialize a scholarly research project without inventing scholarship."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import shutil
import subprocess
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

_SCRIPTS_ROOT = next(parent for parent in Path(__file__).resolve().parents if parent.name == "scripts")
_LIB_DIR = _SCRIPTS_ROOT / "lib"
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

from import_paths import configure_script_paths
from project_config import change_to_project_root
from script_utils import read_text, replace_placeholders, write_text_file

configure_script_paths(__file__)

GENERATED_MARKER = "Generated by scripts/start_project.py"
UNRESOLVED_TEXT = "Unresolved: decide later."
STRICT_UNRESOLVED_TEXT = "TODO: decide later."
PROJECT_START_PATH = Path("project-start.yml")
PROJECT_CHARTER_PATH = Path("notes/00-inbox/project-charter.md")
PROJECT_CHARTER_TEMPLATE_PATH = Path("templates/project-charter-template.md")
QUARTO_CONFIG_PATH = Path("manuscript/_quarto.yml")
MANUSCRIPT_INDEX_PATH = Path("manuscript/index.qmd")
FRONT_MATTER_PATH = Path("manuscript/chapters/00-front-matter.qmd")
BACK_MATTER_PATH = Path("manuscript/chapters/99-back-matter.qmd")
DEFAULT_BIBLIOGRAPHY_PATH = Path("bibliography/references.bib")
KNOWN_QUARTO_FORMATS = ("html", "pdf", "docx")
UNKNOWN_VALUES = {"", "unknown", "unknown yet", "decide later", "undecided", "not sure", "n/a", "na"}
PROJECT_TYPES = {"book", "article", "thesis-style manuscript", "mixed paper/book project"}

SCAFFOLD_MARKERS_BY_PATH = {
    QUARTO_CONFIG_PATH: (
        "Research Scaffold Verification Manuscript",
        "Untitled Scholarly Manuscript",
        "chapters/01-chapter-template.qmd",
        "appendices/appendix-template.qmd",
    ),
    MANUSCRIPT_INDEX_PATH: (
        "This manuscript scaffold is generic",
        "Replace this page with project-level front matter",
        "quartoPdfBasics",
    ),
    FRONT_MATTER_PATH: (
        "Use this file for generic front matter",
    ),
    BACK_MATTER_PATH: (
        "Use this file for references to appendices",
    ),
}


@dataclass(frozen=True)
class Question:
    key: str
    prompt: str
    default: str = ""
    multi: bool = False


QUESTIONS = (
    Question("working_title", "Working title"),
    Question("subtitle", "Subtitle (optional)"),
    Question("author_name", "Author/display name"),
    Question("project_slug", "Project slug"),
    Question("project_type", "Project type: book, article, thesis-style manuscript, or mixed paper/book project", "book"),
    Question("central_research_question", "Central research question"),
    Question("working_thesis", "Working thesis, or unknown yet", "unknown yet"),
    Question("primary_audience", "Primary audience"),
    Question("secondary_audience", "Secondary audience (optional)"),
    Question("fields_disciplines", "Field/disciplines involved (comma-separated)", multi=True),
    Question("theories_to_engage", "Theories/traditions to engage (comma-separated)", multi=True),
    Question("contested_theories", "Theories/traditions requiring careful wording (comma-separated)", multi=True),
    Question("scope_included", "Scope included (comma-separated)", multi=True),
    Question("scope_excluded", "Scope excluded (comma-separated)", multi=True),
    Question("main_uncertainties", "Main uncertainties / open questions (comma-separated)", multi=True),
    Question("initial_research_tasks", "Initial research tasks (comma-separated)", multi=True),
    Question("output_formats", "Desired output formats: html, pdf, docx, other (comma-separated)", "html", multi=True),
    Question("chapter_names", "Initial chapter/section names, or blank for default placeholders", multi=True),
    Question("citation_style", "Citation style if known, otherwise undecided", "undecided"),
    Question("target_venue", "Target venue/publisher if known, otherwise undecided", "undecided"),
    Question("bibliography_path", "Bibliography file path", DEFAULT_BIBLIOGRAPHY_PATH.as_posix()),
    Question("better_bibtex_auto_export", "Is Better BibTeX auto-export already configured? yes/no/not sure", "not sure"),
    Question("use_obsidian", "Will Obsidian be used? yes/no/not sure", "not sure"),
    Question("use_codex_agents", "Will Codex/Codex Panel/local agents be used? yes/no/not sure", "not sure"),
    Question("strict_placeholder_detection", "Use strict placeholder detection before release/export? yes/no", "yes"),
    Question("run_audit_after_initialization", "Run local audit after initialization? yes/no", "no"),
    Question("render_after_initialization", "Render manuscript after initialization if tools are available? yes/no", "no"),
)

LIST_KEYS = {question.key for question in QUESTIONS if question.multi}
ANSWER_KEYS = tuple(question.key for question in QUESTIONS)


@dataclass(frozen=True)
class StartProjectOptions:
    dry_run: bool = False
    force: bool = False
    skip_audit: bool = False
    skip_render: bool = False


@dataclass(frozen=True)
class PlannedChange:
    path: Path
    content: str


@dataclass
class StartProjectResult:
    planned_files: list[Path] = field(default_factory=list)
    changed_files: list[Path] = field(default_factory=list)
    unchanged_files: list[Path] = field(default_factory=list)
    skipped_files: list[Path] = field(default_factory=list)
    protected_force_files: list[Path] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    failed: list[str] = field(default_factory=list)
    dry_run_diffs: list[str] = field(default_factory=list)
    commands_run: list[str] = field(default_factory=list)
    commands_skipped: list[str] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)
    exit_code: int = 0


CommandRunner = Callable[[Sequence[str], Path], subprocess.CompletedProcess[str]]
WhichFunc = Callable[[str], str | None]


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Preview changes and commands without writing files.")
    parser.add_argument("--answers", help="Read project answers from a JSON or simple YAML file.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace scaffold-owned or explicitly protected targets that already contain content.",
    )
    parser.add_argument("--skip-audit", action="store_true", help="Do not run post-initialization audit commands.")
    parser.add_argument("--skip-render", action="store_true", help="Do not render the manuscript after initialization.")
    parser.add_argument("--non-interactive", action="store_true", help="Require --answers and never prompt for input.")
    return parser.parse_args(argv)


def default_chapter_names(project_type: str) -> list[str]:
    normalized = normalize_project_type(project_type)
    if normalized == "article":
        return ["Introduction", "Literature review", "Research approach", "Analysis", "Conclusion"]
    if normalized == "thesis-style manuscript":
        return ["Introduction", "Literature review", "Methodology", "Findings", "Discussion", "Conclusion"]
    if normalized == "mixed paper/book project":
        return ["Introduction", "Literature map", "Core argument", "Case or evidence chapter", "Conclusion"]
    return ["Introduction", "Literature map", "Evidence base", "Argument development", "Conclusion"]


def collect_interactive_answers(
    *,
    input_func: Callable[[str], str] = input,
    existing_answers: Mapping[str, object] | None = None,
) -> dict[str, object]:
    answers = dict(existing_answers or {})
    for question in QUESTIONS:
        current = answers.get(question.key)
        if current not in (None, "", []):
            continue
        default_text = f" [{question.default}]" if question.default else ""
        prompt = f"{question.prompt}{default_text} (enter unknown/decide later if unresolved): "
        raw_value = input_func(prompt).strip()
        if raw_value == "" and question.default:
            raw_value = question.default
        answers[question.key] = split_list(raw_value) if question.multi else raw_value
    return normalize_answers(answers)


def load_answers_file(path: Path) -> dict[str, object]:
    text = read_text(path)
    if path.suffix.lower() == ".json":
        loaded = json.loads(text)
        if not isinstance(loaded, dict):
            raise ValueError("Answers JSON must contain an object at the top level.")
        return dict(loaded)
    if path.suffix.lower() in {".yml", ".yaml"}:
        return parse_simple_yaml(text)
    raise ValueError(f"Unsupported answers file extension: {path.suffix}. Use .json, .yml, or .yaml.")


def load_resume_answers(project_root: Path) -> tuple[dict[str, object], list[str]]:
    answers_path = project_root / PROJECT_START_PATH
    if not answers_path.exists():
        return {}, []
    return load_answers_file(answers_path), [f"Resumed answers from {PROJECT_START_PATH}."]


def parse_simple_yaml(text: str) -> dict[str, object]:
    answers: dict[str, object] = {}
    current_list_key: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line.startswith("  - ") and current_list_key:
            answers.setdefault(current_list_key, [])
            list_value = answers[current_list_key]
            if not isinstance(list_value, list):
                raise ValueError(f"YAML key {current_list_key!r} mixes scalar and list values.")
            list_value.append(parse_yaml_scalar(line[4:].strip()))
            continue
        current_list_key = None
        if ":" not in line:
            raise ValueError(f"Unsupported YAML line: {line!r}")
        key, raw_value = line.split(":", 1)
        key = key.strip()
        if key not in ANSWER_KEYS:
            continue
        value = raw_value.strip()
        if value == "":
            if key in LIST_KEYS:
                answers[key] = []
                current_list_key = key
            else:
                answers[key] = ""
        else:
            answers[key] = parse_yaml_scalar(value)
    return answers


def parse_yaml_scalar(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        if value[0] == '"':
            return str(json.loads(value))
        return value[1:-1].replace("''", "'")
    return value


def dump_answers_yaml(answers: Mapping[str, object]) -> str:
    lines = [
        f"# {GENERATED_MARKER}",
        "# This file records project-start answers; it is not evidence or bibliography metadata.",
    ]
    for key in ANSWER_KEYS:
        value = answers.get(key, "")
        if key in LIST_KEYS:
            values = ensure_string_list(value)
            lines.append(f"{key}:")
            if values:
                lines.extend(f"  - {format_yaml_scalar(item)}" for item in values)
            continue
        lines.append(f"{key}: {format_yaml_scalar(string_value(value))}")
    lines.append("")
    return "\n".join(lines)


def format_yaml_scalar(value: str) -> str:
    if value == "":
        return '""'
    unsafe = re.search(r"[:#\[\]{}&*!|>'\"%@`]", value) or value.strip() != value
    yaml_keyword = value.lower() in {"true", "false", "yes", "no", "null", "~"}
    if unsafe or yaml_keyword:
        return json.dumps(value)
    return value


def normalize_answers(raw_answers: Mapping[str, object]) -> dict[str, object]:
    normalized: dict[str, object] = {}
    for question in QUESTIONS:
        raw_value = raw_answers.get(question.key, question.default)
        if question.multi:
            normalized[question.key] = normalize_list(raw_value)
            continue
        normalized[question.key] = normalize_scalar(raw_value, question.default)

    normalized["working_title"] = normalize_required_text(normalized["working_title"], "Untitled project")
    normalized["author_name"] = unresolved_text(normalized["author_name"])
    normalized["project_type"] = normalize_project_type(string_value(normalized["project_type"]))
    normalized["project_slug"] = normalize_project_slug(
        string_value(normalized["project_slug"]),
        string_value(normalized["working_title"]),
    )
    normalized["central_research_question"] = unresolved_text(normalized["central_research_question"])
    normalized["working_thesis"] = normalize_required_text(normalized["working_thesis"], "unknown yet")
    normalized["primary_audience"] = unresolved_text(normalized["primary_audience"])
    normalized["secondary_audience"] = unresolved_text(normalized["secondary_audience"], empty_allowed=True)
    normalized["output_formats"] = normalize_output_formats(normalized["output_formats"])
    if not normalized["chapter_names"]:
        normalized["chapter_names"] = default_chapter_names(string_value(normalized["project_type"]))
    normalized["citation_style"] = normalize_required_text(normalized["citation_style"], "undecided")
    normalized["target_venue"] = normalize_required_text(normalized["target_venue"], "undecided")
    normalized["bibliography_path"] = normalize_required_text(
        normalized["bibliography_path"],
        DEFAULT_BIBLIOGRAPHY_PATH.as_posix(),
    )
    return normalized


def normalize_project_type(value: str) -> str:
    lowered = value.strip().lower()
    if lowered in {"thesis", "thesis-style", "thesis style", "thesis-style manuscript"}:
        return "thesis-style manuscript"
    if lowered in {"mixed", "mixed paper/book", "paper/book", "mixed paper/book project"}:
        return "mixed paper/book project"
    if lowered in PROJECT_TYPES:
        return lowered
    if lowered in UNKNOWN_VALUES:
        return "book"
    return lowered


def normalize_required_text(value: object, fallback: str) -> str:
    text = string_value(value).strip()
    return fallback if text.lower() in UNKNOWN_VALUES else text


def normalize_scalar(value: object, default: str) -> str:
    text = string_value(value).strip()
    if text == "" and default:
        return default
    return text


def unresolved_text(value: object, *, empty_allowed: bool = False) -> str:
    text = string_value(value).strip()
    if empty_allowed and text == "":
        return ""
    return UNRESOLVED_TEXT if text.lower() in UNKNOWN_VALUES else text


def normalize_list(value: object) -> list[str]:
    return [item for item in ensure_string_list(value) if item.strip().lower() not in UNKNOWN_VALUES]


def normalize_output_formats(value: object) -> list[str]:
    values = [item.lower() for item in normalize_list(value)]
    if not values:
        return ["html"]
    unique_values: list[str] = []
    for item in values:
        normalized = item.strip().lower()
        if normalized == "word":
            normalized = "docx"
        if normalized not in unique_values:
            unique_values.append(normalized)
    return unique_values


def split_list(value: str) -> list[str]:
    return [item.strip() for item in re.split(r"[,;\n]", value) if item.strip()]


def ensure_string_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [string_value(item).strip() for item in value if string_value(item).strip()]
    if isinstance(value, tuple):
        return [string_value(item).strip() for item in value if string_value(item).strip()]
    return split_list(string_value(value))


def string_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return str(value)


def normalize_project_slug(raw_slug: str, title: str) -> str:
    slug = slugify(raw_slug or title or "research-project")
    if not slug:
        slug = "research-project"
    return avoid_forbidden_codex_prefix(slug, "project")


def slugify(value: str) -> str:
    lowered = value.strip().lower()
    replaced = re.sub(r"[^a-z0-9]+", "-", lowered)
    return replaced.strip("-")


def avoid_forbidden_codex_prefix(slug: str, replacement_prefix: str) -> str:
    if slug.lower().startswith("codex"):
        return f"{replacement_prefix}-{slug}"
    return slug


def build_planned_changes(project_root: Path, answers: Mapping[str, object], result: StartProjectResult) -> list[PlannedChange]:
    changes = [
        PlannedChange(project_root / PROJECT_START_PATH, dump_answers_yaml(answers)),
        PlannedChange(project_root / QUARTO_CONFIG_PATH, render_quarto_config(project_root, answers)),
        PlannedChange(project_root / MANUSCRIPT_INDEX_PATH, render_manuscript_index(answers)),
        PlannedChange(project_root / FRONT_MATTER_PATH, render_front_matter(answers)),
        PlannedChange(project_root / BACK_MATTER_PATH, render_back_matter(answers)),
    ]
    charter = render_project_charter(project_root, answers, result)
    if charter is not None:
        changes.append(PlannedChange(project_root / PROJECT_CHARTER_PATH, charter))
    for relative_path, content in render_chapter_files(answers).items():
        changes.append(PlannedChange(project_root / relative_path, content))
    bibliography_change = render_bibliography_placeholder(project_root, answers)
    if bibliography_change is not None:
        changes.append(PlannedChange(bibliography_change[0], bibliography_change[1]))
    return changes


def render_project_charter(
    project_root: Path,
    answers: Mapping[str, object],
    result: StartProjectResult,
) -> str | None:
    template_path = project_root / PROJECT_CHARTER_TEMPLATE_PATH
    if not template_path.exists():
        result.warnings.append(f"Missing {PROJECT_CHARTER_TEMPLATE_PATH}; skipped project charter.")
        return None
    template = read_text(template_path)
    unresolved = unresolved_marker(answers)
    replacements = {
        "TITLE": string_value(answers["working_title"]),
        "PURPOSE": project_purpose(answers),
        "PRIMARY_READERS": display_scalar(answers, "primary_audience"),
        "QUESTION": display_scalar(answers, "central_research_question"),
        "IN_SCOPE_BOUNDARY": first_or_unresolved(answers["scope_included"], unresolved),
        "OUT_OF_SCOPE_BOUNDARY": first_or_unresolved(answers["scope_excluded"], unresolved),
        "KNOWN_SOURCE_BASE": source_base_text(answers),
        "KEY_UNCERTAINTY": first_or_unresolved(answers["main_uncertainties"], unresolved),
        "FIRST_RESEARCH_TASK": first_or_unresolved(answers["initial_research_tasks"], unresolved),
    }
    body = replace_placeholders(template, replacements).rstrip()
    body = append_list_items(body, "### In scope", answers["scope_included"])
    body = append_list_items(body, "### Out of scope", answers["scope_excluded"])
    body = append_list_items(body, "## Key uncertainties", answers["main_uncertainties"])
    body = append_list_items(body, "## First research tasks", answers["initial_research_tasks"])
    return "\n\n".join([generated_html_comment(), body, render_charter_extension(answers)]).rstrip() + "\n"


def append_list_items(text: str, heading: str, values: object) -> str:
    items = ensure_string_list(values)
    if len(items) <= 1 or heading not in text:
        return text
    first_item = first_or_unresolved(items)
    extra_items = [item for item in items[1:] if item != first_item]
    if not extra_items:
        return text
    insertion = "\n".join(f"- {item}" for item in extra_items)
    return text.replace(f"- {first_item}", f"- {first_item}\n{insertion}", 1)


def render_charter_extension(answers: Mapping[str, object]) -> str:
    unresolved = unresolved_marker(answers)
    sections = [
        "## Scholarly framing",
        "",
        f"- Project type: {answers['project_type']}",
        f"- Working thesis: {display_scalar(answers, 'working_thesis')}",
        f"- Secondary audience: {optional_or_unresolved(answers['secondary_audience'], unresolved)}",
        f"- Fields/disciplines: {inline_list_or_unresolved(answers['fields_disciplines'], unresolved)}",
        f"- Theories/traditions to engage: {inline_list_or_unresolved(answers['theories_to_engage'], unresolved)}",
        f"- Contested traditions requiring careful wording: {inline_list_or_unresolved(answers['contested_theories'], unresolved)}",
        "",
        "## Manuscript setup",
        "",
        f"- Desired output formats: {inline_list_or_unresolved(answers['output_formats'])}",
        f"- Initial chapters/sections: {inline_list_or_unresolved(answers['chapter_names'])}",
        f"- Citation style: {answers['citation_style']}",
        f"- Target venue/publisher: {answers['target_venue']}",
        "",
        "## Citation and workflow setup",
        "",
        f"- Citation source of truth: Zotero + Better BibTeX export or `{answers['bibliography_path']}`.",
        *citation_readiness_notes(answers),
        f"- Obsidian use: {answers['use_obsidian']}",
        f"- Codex/Codex Panel/local agents: {answers['use_codex_agents']}",
        f"- Strict placeholder detection before release/export: {answers['strict_placeholder_detection']}",
        "",
        "## Evidence boundary",
        "",
        (
            "This charter records project-start decisions only. It does not supply citations, source metadata, "
            "page numbers, quotations, or final claims."
        ),
    ]
    return "\n".join(sections)


def render_quarto_config(project_root: Path, answers: Mapping[str, object]) -> str:
    chapter_paths = ["index.qmd", "chapters/00-front-matter.qmd"]
    chapter_paths.extend(path.as_posix() for path in chapter_quarto_paths(answers))
    chapter_paths.append("chapters/99-back-matter.qmd")

    lines = [
        f"# {GENERATED_MARKER}",
        "project:",
        "  type: book",
        "  output-dir: ../exports/html",
        "",
        "book:",
        f"  title: {quote_quarto_value(answers['working_title'])}",
    ]
    if not is_unresolved(answers["subtitle"]):
        lines.append(f"  subtitle: {quote_quarto_value(answers['subtitle'])}")
    if not is_unresolved(answers["author_name"]):
        lines.append(f"  author: {quote_quarto_value(answers['author_name'])}")
    lines.append("  chapters:")
    lines.extend(f"    - {chapter_path}" for chapter_path in chapter_paths)
    lines.extend(
        [
            "",
            f"bibliography: ../{answers['bibliography_path']}",
            "",
            "format:",
        ]
    )
    quarto_formats = [item for item in ensure_string_list(answers["output_formats"]) if item in KNOWN_QUARTO_FORMATS]
    if not quarto_formats:
        quarto_formats = ["html"]
    for output_format in quarto_formats:
        lines.extend([f"  {output_format}:", "    toc: true"])
    lines.append("")
    return "\n".join(lines)


def quote_quarto_value(value: object) -> str:
    return json.dumps(string_value(value))


def render_front_matter(answers: Mapping[str, object]) -> str:
    unresolved = unresolved_marker(answers)
    sections = [
        generated_html_comment(),
        f"# Front matter for {answers['working_title']}",
        "",
        "## Project note",
        "",
        (
            "This front matter records initialization context only. Replace it with final acknowledgments, "
            "preface, author notes, or other front matter when those materials are ready."
        ),
        "",
        "## Initialization context",
        "",
        f"- Project type: {answers['project_type']}",
        f"- Author/display name: {display_scalar(answers, 'author_name')}",
        f"- Primary audience: {display_scalar(answers, 'primary_audience')}",
        f"- Secondary audience: {optional_or_unresolved(answers['secondary_audience'], unresolved)}",
        "",
    ]
    return "\n".join(sections)


def render_back_matter(answers: Mapping[str, object]) -> str:
    sections = [
        generated_html_comment(),
        f"# Back matter for {answers['working_title']}",
        "",
        "## Reference boundary",
        "",
        f"- Bibliography path: `{answers['bibliography_path']}`",
        f"- Citation style: {answers['citation_style']}",
        *citation_readiness_notes(answers),
        (
            "- Add glossary entries, appendix references, or closing materials only after they are tied to "
            "project notes, claim records, or verified manuscript needs."
        ),
        "",
    ]
    return "\n".join(sections)


def render_manuscript_index(answers: Mapping[str, object]) -> str:
    unresolved = unresolved_marker(answers)
    sections = [
        generated_html_comment(),
        f"# {answers['working_title']}",
        "",
        "This page records project scope and unresolved decisions before drafting begins. It is not final argument.",
        "",
        "## Project frame",
        "",
        f"- Project type: {answers['project_type']}",
        f"- Author/display name: {display_scalar(answers, 'author_name')}",
        f"- Primary audience: {display_scalar(answers, 'primary_audience')}",
        f"- Secondary audience: {optional_or_unresolved(answers['secondary_audience'], unresolved)}",
        f"- Target venue/publisher: {answers['target_venue']}",
        "",
        "## Central research question",
        "",
        display_scalar(answers, "central_research_question"),
        "",
        "## Working thesis",
        "",
        display_scalar(answers, "working_thesis"),
        "",
        "## Scope",
        "",
        "### Included",
        "",
        bullet_list_or_unresolved(answers["scope_included"], unresolved),
        "",
        "### Excluded",
        "",
        bullet_list_or_unresolved(answers["scope_excluded"], unresolved),
        "",
        "## Uncertainties and first research tasks",
        "",
        "### Open questions",
        "",
        bullet_list_or_unresolved(answers["main_uncertainties"], unresolved),
        "",
        "### First research tasks",
        "",
        bullet_list_or_unresolved(answers["initial_research_tasks"], unresolved),
        "",
        "## Citation boundary",
        "",
        f"- Bibliography path: `{answers['bibliography_path']}`",
        f"- Citation style: {answers['citation_style']}",
        *citation_readiness_notes(answers),
        (
            "- Add citations only after the citekey exists in the bibliography source of truth. "
            "Do not add generated bibliography records."
        ),
        "",
    ]
    return "\n".join(sections)


def render_chapter_files(answers: Mapping[str, object]) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for relative_path, chapter_name in zip(chapter_file_paths(answers), ensure_string_list(answers["chapter_names"])):
        files[relative_path] = render_chapter_stub(chapter_name, answers)
    return files


def render_chapter_stub(chapter_name: str, answers: Mapping[str, object]) -> str:
    unresolved = unresolved_marker(answers)
    return "\n".join(
        [
            generated_html_comment(),
            f"# {chapter_name}",
            "",
            "## Purpose",
            "",
            f"{unresolved} Define this chapter or section after the evidence base and claim ledger are developed.",
            "",
            "## Evidence status",
            "",
            (
                "No chapter claims are drafted yet. Add only material traceable to source notes, claim records, "
                "chapter briefs, and verified citekeys."
            ),
            "",
            "## Related project question",
            "",
            display_scalar(answers, "central_research_question"),
            "",
            "## Open issues",
            "",
            bullet_list_or_unresolved(answers["main_uncertainties"], unresolved),
            "",
        ]
    )


def chapter_file_paths(answers: Mapping[str, object]) -> list[Path]:
    paths: list[Path] = []
    for index, slug in enumerate(chapter_slugs(answers), start=1):
        paths.append(Path("manuscript") / "chapters" / f"{index:02d}-{slug}.qmd")
    return paths


def chapter_quarto_paths(answers: Mapping[str, object]) -> list[Path]:
    paths: list[Path] = []
    for index, slug in enumerate(chapter_slugs(answers), start=1):
        paths.append(Path("chapters") / f"{index:02d}-{slug}.qmd")
    return paths


def chapter_slugs(answers: Mapping[str, object]) -> list[str]:
    slugs: list[str] = []
    for index, chapter_name in enumerate(ensure_string_list(answers["chapter_names"]), start=1):
        slug = slugify(chapter_name) or f"section-{index}"
        slug = avoid_forbidden_codex_prefix(slug, "section")
        slugs.append(slug)
    return slugs


def render_bibliography_placeholder(project_root: Path, answers: Mapping[str, object]) -> tuple[Path, str] | None:
    bibliography_path = project_root / string_value(answers["bibliography_path"])
    if bibliography_path.exists() and read_text(bibliography_path).strip():
        return None
    text = "\n".join(
        [
            "% Bibliography source of truth for this project.",
            "% Add only verified BibTeX records exported from Zotero or another verified bibliography workflow.",
            f"% Better BibTeX auto-export status: {answers['better_bibtex_auto_export']}",
            "",
        ]
    )
    return bibliography_path, text


def apply_change(
    change: PlannedChange,
    options: StartProjectOptions,
    result: StartProjectResult,
) -> None:
    result.planned_files.append(change.path)
    if change.path.exists():
        existing_text = read_text(change.path)
        if existing_text == change.content:
            result.unchanged_files.append(change.path)
            return
        if not is_safe_to_replace(change.path, existing_text):
            if not options.force:
                warning = skipped_change_warning(change.path, existing_text)
                result.warnings.append(warning)
                result.skipped_files.append(change.path)
                if options.dry_run:
                    result.dry_run_diffs.append(render_diff(change.path, existing_text, change.content))
                return
            result.protected_force_files.append(change.path)
            if options.dry_run:
                result.warnings.append(f"Dry-run: --force would replace protected content: {change.path}")
            else:
                result.warnings.append(f"Replacing protected content because --force was supplied: {change.path}")
            if options.dry_run:
                result.dry_run_diffs.append(render_diff(change.path, existing_text, change.content))
                return
        if options.dry_run:
            result.dry_run_diffs.append(render_diff(change.path, existing_text, change.content))
            return
    elif options.dry_run:
        result.dry_run_diffs.append(render_diff(change.path, "", change.content))
        return

    write_text_file(change.path, change.content)
    result.changed_files.append(change.path)


def is_safe_to_replace(path: Path, existing_text: str) -> bool:
    relative_path = relative_to_projectish(path)
    markers = SCAFFOLD_MARKERS_BY_PATH.get(relative_path, ())
    return any(marker in existing_text for marker in markers)


def skipped_change_warning(path: Path, existing_text: str) -> str:
    if GENERATED_MARKER in existing_text:
        return (
            f"Skipped {path}: generated file differs from the planned initializer output; "
            "rerun with --force only if those local edits should be replaced."
        )
    return f"Skipped {path}: non-scaffold content is present; rerun with --force to replace it."


def relative_to_projectish(path: Path) -> Path:
    parts = path.parts
    for marker in ("manuscript", "notes", "research", "bibliography", "templates"):
        if marker in parts:
            return Path(*parts[parts.index(marker) :])
    return Path(path.name)


def render_diff(path: Path, old_text: str, new_text: str) -> str:
    old_lines = old_text.splitlines(keepends=True)
    new_lines = new_text.splitlines(keepends=True)
    return "".join(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"{path} (current)",
            tofile=f"{path} (planned)",
        )
    )


def project_relative_path(
    project_root: Path,
    raw_path: str,
    fallback: Path,
    result: StartProjectResult,
) -> str:
    project_root_resolved = project_root.resolve()
    requested_path = Path(raw_path).expanduser()
    candidate = requested_path if requested_path.is_absolute() else project_root / requested_path
    resolved = candidate.resolve()
    try:
        return resolved.relative_to(project_root_resolved).as_posix()
    except ValueError:
        result.warnings.append(
            f"Bibliography path {raw_path!r} is outside the project root; using {fallback.as_posix()}."
        )
        return fallback.as_posix()


def initialize_project(
    project_root: Path,
    answers: Mapping[str, object],
    options: StartProjectOptions,
    *,
    runner_func: CommandRunner | None = None,
    which_func: WhichFunc = shutil.which,
) -> StartProjectResult:
    normalized_answers = normalize_answers(answers)
    result = StartProjectResult()
    normalized_answers["bibliography_path"] = project_relative_path(
        project_root,
        string_value(normalized_answers["bibliography_path"]),
        DEFAULT_BIBLIOGRAPHY_PATH,
        result,
    )
    for warning in answer_warnings(normalized_answers):
        result.warnings.append(warning)
    for change in build_planned_changes(project_root, normalized_answers, result):
        apply_change(change, options, result)

    run_post_initialization(project_root, normalized_answers, options, result, runner_func, which_func)
    result.next_steps.extend(manual_next_steps(project_root, normalized_answers, options, which_func))
    result.exit_code = 1 if result.failed else 0
    return result


def answer_warnings(answers: Mapping[str, object]) -> list[str]:
    warnings: list[str] = []
    unknown_formats = [item for item in ensure_string_list(answers["output_formats"]) if item not in KNOWN_QUARTO_FORMATS]
    if unknown_formats:
        warnings.append(
            "Unsupported Quarto output format(s) recorded but not added to manuscript/_quarto.yml: "
            + ", ".join(unknown_formats)
        )
    better_bibtex_status = string_value(answers["better_bibtex_auto_export"]).lower()
    if better_bibtex_status == "no":
        warnings.append("Better BibTeX auto-export is not configured; set it up before citing Zotero sources.")
    elif better_bibtex_status != "yes":
        warnings.append("Better BibTeX auto-export is unresolved; verify Zotero export before citing sources.")
    return warnings


def manual_next_steps(
    project_root: Path,
    answers: Mapping[str, object],
    options: StartProjectOptions,
    which_func: WhichFunc,
) -> list[str]:
    steps: list[str] = []
    bibliography_path = string_value(answers["bibliography_path"])
    bibliography_file = project_root / bibliography_path
    better_bibtex_status = string_value(answers["better_bibtex_auto_export"]).lower()
    if better_bibtex_status != "yes":
        steps.append(f"Set up Zotero + Better BibTeX auto-export to `{bibliography_path}` before citing sources.")
    if not bibliography_has_verified_entries(bibliography_file):
        steps.append(f"Export verified references into `{bibliography_path}` before adding manuscript citations.")
    if is_unresolved(answers["citation_style"]):
        steps.append("Choose a citation style before release or publisher-specific export.")
    if is_unresolved(answers["target_venue"]):
        steps.append("Record the target venue or publisher once that decision is known.")
    if should_run_step(answers["use_obsidian"]):
        steps.append("Open this repository as the Obsidian vault before relying on Obsidian-only links or views.")
    if should_run_step(answers["strict_placeholder_detection"]):
        steps.append("Resolve release-check-visible placeholders before sharing or exporting the manuscript.")
    if should_run_step(answers["render_after_initialization"]) and not options.skip_render and not which_func("quarto"):
        steps.append("Install Quarto before rendering the manuscript.")
    if not steps:
        steps.append("Review the generated files, then run `make audit`.")
    return steps


def bibliography_has_verified_entries(path: Path) -> bool:
    if not path.exists():
        return False
    for line in read_text(path).splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("%"):
            return True
    return False


def run_post_initialization(
    project_root: Path,
    answers: Mapping[str, object],
    options: StartProjectOptions,
    result: StartProjectResult,
    runner_func: CommandRunner | None,
    which_func: WhichFunc,
) -> None:
    runner = runner_func or default_command_runner
    if should_run_step(answers["run_audit_after_initialization"]) and not options.skip_audit:
        run_command(["bash", "setup.sh", "--dry-run"], project_root, "setup dry-run", options, result, runner)
        run_command(
            ["python3", "scripts/research-writing/check_manuscript_readiness.py"],
            project_root,
            "manuscript readiness check",
            options,
            result,
            runner,
        )
        run_command(["make", "audit"], project_root, "repository audit", options, result, runner)
    elif options.skip_audit:
        result.commands_skipped.append("post-initialization audit skipped by --skip-audit")

    if should_run_step(answers["render_after_initialization"]) and not options.skip_render:
        run_optional_render(project_root, answers, options, result, runner, which_func)
    elif options.skip_render:
        result.commands_skipped.append("manuscript render skipped by --skip-render")


def default_command_runner(command: Sequence[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(list(command), cwd=cwd, check=False, text=True)


def run_command(
    command: Sequence[str],
    project_root: Path,
    label: str,
    options: StartProjectOptions,
    result: StartProjectResult,
    runner: CommandRunner,
) -> None:
    printable = " ".join(command)
    if options.dry_run:
        result.commands_skipped.append(f"dry-run would run {printable}")
        return
    try:
        command_result = runner(command, project_root)
    except OSError as error:
        result.failed.append(f"{label} failed to start: {error}")
        return
    result.commands_run.append(printable)
    if command_result.returncode != 0:
        result.failed.append(f"{label} exited {command_result.returncode}: {printable}")


def run_optional_render(
    project_root: Path,
    answers: Mapping[str, object],
    options: StartProjectOptions,
    result: StartProjectResult,
    runner: CommandRunner,
    which_func: WhichFunc,
) -> None:
    if not which_func("quarto"):
        result.warnings.append("Quarto is not available; skipped optional manuscript render.")
        return
    output_format = first_supported_render_format(answers)
    command = ["bash", "scripts/research-writing/render.sh"]
    if output_format:
        command.extend(["--to", output_format])
    if options.dry_run:
        result.commands_skipped.append(f"dry-run would run {' '.join(command)}")
        return
    try:
        render_result = runner(command, project_root)
    except OSError as error:
        result.warnings.append(f"Optional render failed to start: {error}")
        return
    result.commands_run.append(" ".join(command))
    if render_result.returncode != 0:
        result.warnings.append(f"Optional render exited {render_result.returncode}; inspect render output before export.")


def first_supported_render_format(answers: Mapping[str, object]) -> str | None:
    for output_format in ensure_string_list(answers["output_formats"]):
        if output_format in KNOWN_QUARTO_FORMATS:
            return output_format
    return None


def should_run_step(value: object) -> bool:
    return string_value(value).strip().lower() in {"y", "yes", "true", "1"}


def print_preflight_summary(project_root: Path, answers: Mapping[str, object], which_func: WhichFunc) -> None:
    print_text_section("Preflight summary", preflight_summary_lines(project_root, answers, which_func))


def preflight_summary_lines(project_root: Path, answers: Mapping[str, object], which_func: WhichFunc) -> list[str]:
    bibliography_path = string_value(answers.get("bibliography_path")) or DEFAULT_BIBLIOGRAPHY_PATH.as_posix()
    bibliography_file, bibliography_display = preflight_bibliography_path(project_root, bibliography_path)
    target_paths = [
        PROJECT_START_PATH,
        QUARTO_CONFIG_PATH,
        MANUSCRIPT_INDEX_PATH,
        PROJECT_CHARTER_PATH,
    ]
    existing_targets = [path.as_posix() for path in target_paths if (project_root / path).exists()]
    return [
        f"Existing {PROJECT_START_PATH}: {found_text(project_root / PROJECT_START_PATH)}",
        f"Bibliography path: {bibliography_display} ({bibliography_status(bibliography_file)})",
        f"Quarto: {tool_status('quarto', which_func)}",
        f"Pandoc: {tool_status('pandoc', which_func)}",
        f"Audit target: {make_target_status(project_root, 'audit')}",
        "Initializer targets already present: " + (", ".join(existing_targets) if existing_targets else "none"),
    ]


def preflight_bibliography_path(project_root: Path, raw_path: str) -> tuple[Path, str]:
    project_root_resolved = project_root.resolve()
    requested_path = Path(raw_path).expanduser()
    candidate = requested_path if requested_path.is_absolute() else project_root / requested_path
    try:
        relative_path = candidate.resolve().relative_to(project_root_resolved)
    except ValueError:
        fallback = project_root / DEFAULT_BIBLIOGRAPHY_PATH
        return fallback, f"{raw_path} is outside project root; will fall back to {DEFAULT_BIBLIOGRAPHY_PATH.as_posix()}"
    return project_root / relative_path, relative_path.as_posix()


def found_text(path: Path) -> str:
    return "found" if path.exists() else "not found"


def bibliography_status(path: Path) -> str:
    if not path.exists():
        return "missing"
    return "has verified-looking entries" if bibliography_has_verified_entries(path) else "empty or comments only"


def tool_status(tool_name: str, which_func: WhichFunc) -> str:
    return "available" if which_func(tool_name) else "not found"


def make_target_status(project_root: Path, target_name: str) -> str:
    makefile = project_root / "Makefile"
    if not makefile.exists():
        return "not found"
    pattern = re.compile(rf"^{re.escape(target_name)}\s*:")
    return "found" if any(pattern.match(line) for line in read_text(makefile).splitlines()) else "not found"


def print_summary(result: StartProjectResult) -> None:
    print("Project initialization summary")
    print_path_section("Changed files", result.changed_files)
    print_path_section("Unchanged files", result.unchanged_files)
    print_path_section("Skipped files", result.skipped_files)
    print_path_section("Protected files selected by --force", result.protected_force_files)
    print_text_section("Warnings", result.warnings)
    print_text_section("Commands run", result.commands_run)
    print_text_section("Commands skipped", result.commands_skipped)
    print_text_section("Next steps", result.next_steps)
    print_text_section("Failures", result.failed)
    if result.dry_run_diffs:
        print("\nPlanned changes:")
        for diff in result.dry_run_diffs:
            print(diff.rstrip())


def print_path_section(title: str, values: Sequence[Path]) -> None:
    print(f"\n{title}:")
    if not values:
        print("- none")
        return
    for value in values:
        print(f"- {value}")


def print_text_section(title: str, values: Sequence[str]) -> None:
    print(f"\n{title}:")
    if not values:
        print("- none")
        return
    for value in values:
        print(f"- {value}")


def run_cli(
    argv: Sequence[str],
    *,
    project_root: Path | None = None,
    input_func: Callable[[str], str] = input,
    runner_func: CommandRunner | None = None,
    which_func: WhichFunc = shutil.which,
    emit_summary: bool = True,
) -> StartProjectResult:
    args = parse_args(argv)
    root = project_root or Path.cwd()
    if args.non_interactive and not args.answers:
        result = StartProjectResult(exit_code=2)
        result.failed.append("--non-interactive requires --answers.")
        if emit_summary:
            print_summary(result)
        return result

    try:
        startup_warnings: list[str] = []
        if args.answers:
            answers = load_answers_file(Path(args.answers))
        else:
            answers, startup_warnings = load_resume_answers(root)
        if not args.non_interactive:
            if emit_summary:
                print_preflight_summary(root, answers, which_func)
            answers = collect_interactive_answers(input_func=input_func, existing_answers=answers)
        else:
            answers = normalize_answers(answers)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        result = StartProjectResult(exit_code=2)
        result.failed.append(str(error))
        if emit_summary:
            print_summary(result)
        return result

    options = StartProjectOptions(
        dry_run=args.dry_run,
        force=args.force,
        skip_audit=args.skip_audit,
        skip_render=args.skip_render,
    )
    result = initialize_project(root, answers, options, runner_func=runner_func, which_func=which_func)
    result.warnings = startup_warnings + result.warnings
    if emit_summary:
        print_summary(result)
    return result


def generated_html_comment() -> str:
    return f"<!-- {GENERATED_MARKER}; this file records setup decisions, not evidence. -->"


def project_purpose(answers: Mapping[str, object]) -> str:
    return (
        f"Initialize a {answers['project_type']} project around the central question without drafting unsupported "
        "claims before sources, notes, and evidence checks exist."
    )


def source_base_text(answers: Mapping[str, object]) -> str:
    return f"Use Zotero + Better BibTeX or `{answers['bibliography_path']}` as the verified bibliography source of truth."


def citation_readiness_notes(answers: Mapping[str, object]) -> list[str]:
    better_bibtex_status = string_value(answers["better_bibtex_auto_export"])
    notes = [
        f"- Better BibTeX auto-export: {better_bibtex_status}",
        "- Zotero plus Better BibTeX is expected unless this project intentionally maintains the BibTeX file by hand.",
    ]
    if better_bibtex_status.lower() == "yes":
        notes.append("- Verify the Better BibTeX export path before adding manuscript citations.")
    else:
        notes.append("- Do not rely on automatic bibliography updates until Better BibTeX export is configured and checked.")
    return notes


def unresolved_marker(answers: Mapping[str, object]) -> str:
    return STRICT_UNRESOLVED_TEXT if should_run_step(answers.get("strict_placeholder_detection")) else UNRESOLVED_TEXT


def display_scalar(answers: Mapping[str, object], key: str) -> str:
    value = string_value(answers[key])
    return unresolved_marker(answers) if is_unresolved(value) else value


def first_or_unresolved(value: object, marker: str = UNRESOLVED_TEXT) -> str:
    values = ensure_string_list(value)
    return values[0] if values else marker


def bullet_list_or_unresolved(value: object, marker: str = UNRESOLVED_TEXT) -> str:
    values = ensure_string_list(value)
    if not values:
        return f"- {marker}"
    return "\n".join(f"- {item}" for item in values)


def inline_list_or_unresolved(value: object, marker: str = UNRESOLVED_TEXT) -> str:
    values = ensure_string_list(value)
    return ", ".join(values) if values else marker


def optional_or_unresolved(value: object, marker: str = UNRESOLVED_TEXT) -> str:
    text = string_value(value).strip()
    return text if text else marker


def is_unresolved(value: object) -> bool:
    text = string_value(value).strip()
    return text.lower() in UNKNOWN_VALUES or text.startswith("Unresolved:")


def main(argv: Sequence[str]) -> int:
    change_to_project_root()
    result = run_cli(argv, project_root=Path.cwd())
    return result.exit_code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
